[workspace]
authors = ["Ali Khan <alik@robarts.ca>"]
channels = ["conda-forge","khanlab","https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public"]
name = "gradcorrect"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fsl-avwutils = ">=2209.6,<2210"
python = ">=3.14.6,<3.15"

[pypi-dependencies]
gradunwarp = { git = "https://github.com/Washington-University/gradunwarp.git" }

