
name: Publish Docker image
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registries:
    uses: khanlab/actions/.github/workflows/workflow-release_task-deployDocker.yml@v0.3.7
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

